services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && cp -r client/dist client-dist
    startCommand: |
      echo "=== STARTING SERVER ==="
      echo "Current directory: $(pwd)"
      echo "Files in current directory: $(ls -la)"
      echo "Starting server/server.js..."
      node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://week-5-web-sockets-assignment-atienoruth-qcvu.onrender.com