services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: npm install
    startCommand: node bulletproof-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://week-5-web-sockets-assignment-atienoruth-qcvu.onrender.com