services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: npm install && node build-client.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://socket-io-4-no7f.onrender.com 