services:
  - type: web
    name: week-5-web-sockets-assignment-ATIENORUTH-2
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && cp -r client/dist client-dist
    startCommand: |
      echo "=== STARTING FRESH SERVER APP.JS ==="
      echo "Current directory: $(pwd)"
      echo "Files in current directory: $(ls -la)"
      echo "Starting server/app.js..."
      node server/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://week-5-web-sockets-assignment-atienoruth-03k5.onrender.com