services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && mkdir -p client-dist && cp -r client/dist/* client-dist/
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://week-5-web-sockets-assignment-atienoruth-qcvu.onrender.com