services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://socket-io-4-no7f.onrender.com 