services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npx vite build && cd ..
      mkdir -p public
      cp -r client/dist/* public/
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://week-5-web-sockets-assignment-atienoruth-ni3b.onrender.com