services:
  - type: web
    name: socket-io-chat
    env: node
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ..
      npm install
      node build-and-copy.js
    startCommand: cd server && npm install && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://week-5-web-sockets-assignment-atienoruth-ni3b.onrender.com