services:
  - type: web
    name: week-5-web-sockets-assignment-ATIENORUTH-2
    env: node
    buildCommand: |
      echo "=== BUILDING APPLICATION ==="
      npm install
      echo "✅ Dependencies installed"
      echo "✅ Build complete - using embedded HTML"
    startCommand: |
      echo "=== STARTING SERVER ==="
      echo "✅ Using embedded HTML - no file dependencies"
      echo "✅ Server will run on PORT: $PORT"
      node server/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000